name: Check for Screenshots in Pull Request

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-screenshots:
    runs-on: ubuntu-latest

    steps:
    - name: Check PR Description for Screenshots
      uses: actions/github-script@v6
      with:
        script: |
          const { context, core } = require('@actions/github');
          
          const description = context.payload.pull_request.body || "";
          
          // Regex to match markdown image links: ![alt text](image-url)
          const imageRegex = /!\[.*?\]\(.*?\)/g;
          
          // Check for matches
          const hasScreenshots = imageRegex.test(description);
          if (!hasScreenshots) {
            core.setFailed("No screenshots were found in the pull request description. Please add screenshots before merging.");
          } else {
            console.log("Screenshots found in the pull request description.");
          }
